[package]
name = "Test1"
version = "0.1.0"
authors = ["Michele Albrigo <michele.albrigo@univr.it>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
